@url_dev=http://localhost:3033/v1/api/

@api_key=03f7dc427f5ebc3b81ee628d69623e5feab81b8df12d1ef454eea7fb76a353862796405d2681f0ea52517b99b2aa956002020439262ad9b3534080733b9b7a13
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFiN2E2MGMwZTNhZjFhYTM5OTgwZGMiLCJlbWFpbCI6InNob3AxMkBnbWFpbC5jb20iLCJpYXQiOjE3MDU3NjAzNjYsImV4cCI6MTcwNTkzMzE2Nn0.UorIfsQRk2ooKQgJT1tQhoMxsh508OBYLjgk26N8hpQ

@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFiN2E2MGMwZTNhZjFhYTM5OTgwZGMiLCJlbWFpbCI6InNob3AxMkBnbWFpbC5jb20iLCJpYXQiOjE3MDU3NjAzNjYsImV4cCI6MTcwNjM2NTE2Nn0.DfNqZJoZ20qncVg9WZ3TPblDkgYBbzbtnQesZaXrukw

@userId=65ab7a60c0e3af1aa39980dc
### signup
POST {{url_dev}}shop/signup
Content-Type: application/json
X-Api-Key: {{api_key}}

{
    "name":"shop01",
    "email":"shop12@gmail.com",
    "password":"123456"
}


### login
POST {{url_dev}}shop/login
Content-Type: application/json
X-Api-Key: {{api_key}}

{
    "name":"shop01",
    "email":"shop12@gmail.com",
    "password":"123456"
}

### logout
POST {{url_dev}}shop/logout
Content-Type: application/json
X-Api-Key: {{api_key}}
X-Client-Id: {{userId}}
Authorization: {{accessToken}}

### refresh token
POST {{url_dev}}shop/refreshtoken
Content-Type: application/json
X-Api-Key: {{api_key}}
X-Client-Id: {{userId}}
X-Refresh-Token: {{refreshToken}}

